language: csharp
mono: none
dotnet: 2.2
solution: "./${PROJ_NAME}.API/${PROJ_NAME}.API.csproj"
stages:
    -build
    -test
jobs:
    include:
        -stage: build
        script:
        - cd "${APP_NAME}"
        - dotnet build
        -stage: test
        script: 
        - cd "${APP_NAME}"
        - dotnet test /p:CollectCoverage=true /p:Exclude="[xunit.*]*"