language: csharp
mono: none
dotnet: 2.2
solution: "./"
jobs:
    include:
        -stage: build
        script:
        - cd '$APP_NAME'
        - dotnet build
        -stage: test
        script: 
        - cd '$APP_NAME'
        - dotnet test /p:CollectCoverage=true /p:Exclude="[xunit.*]*"