language: csharp
mono: none
dotnet: 2.2
solution: "./CBVinil.API/CBVinil.API.csproj"
stages:
    -build
    -test
jobs:
    include:
        -stage: build
        script:
        - cd "CB Vinil"
        - dotnet build
        -stage: test
        script: 
        - cd "CB Vinil"
        - dotnet test /p:CollectCoverage=true /p:Exclude="[xunit.*]*%2C[CBVinil.Persistence]*%2C[CBVinil.Infrastructure]*"